name: patchwork
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - pip
  - pytest
  - laspy
  - numpy
  - geopandas==0.*
  - shapely>=2.0.3
  # ------------- logging ------------- #
  - loguru
    # --------- hydra configs --------- #
  - hydra-core
  - hydra-colorlog
  # ----------- linting --------------- #
  - flake8
  - rasterio