name: patchwork
channels:
  - conda-forge
dependencies:
  - python==3.11.*
  - pip
  - pytest
  - numpy
  - geopandas==0.*
  - shapely>=2.0.3
  - gdal
  - pdal>=2.8
  - python-pdal
  - rasterio
  # ------------- logging ------------- #
  - loguru
    # --------- hydra configs --------- #
  - hydra-core
  - hydra-colorlog
  # ----------- linting --------------- #
  - pre-commit
  - black
  - flake8
  - pip:

    # Fix for the append_points function (waiting for a release)
    # TODO: use conda again for laspy installation once a new version is released
    - lazrs>=0.7.0
    - git+https://github.com/laspy/laspy.git#egg[lazrs]
    - ign-pdal-tools==1.11.1