# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# disable ouput directory from being created
hydra:  
  output_subdir: null  
  run:  
    dir: .

# disable main.log from being created
defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

filepath:
  RECIPIENT_FILE: null
  DONOR_FILE: null
  OUTPUT_FILE: null
  OUTPUT_INDICES_MAP: null

CRS: 2154

DONOR_CLASS_LIST: [2, 9]
RECIPIENT_CLASS_LIST: [2, 3, 9, 17]

RECIPIENT_SUFFIX: "_recipient"
TILE_SIZE: 1000
PATCH_SIZE: 1 # size of a patch of the grid. Must be a divisor of TILE_SIZE, so for 1000: 0.25, 0.5, 2, 4, 5, 10, 25...
NEW_COLUMN: False # True if we want to add a column to mark the added points 
NEW_COLUMN_SIZE: 8  # must be 8, 16, 32 or 64
VALUE_ADDED_POINTS: 1 # in case of a new column, value of the new point (the other are set to 0)
VIRTUAL_CLASS_TRANSLATION: {2: 69, 9: 70}  # if there is no new column, translate the class of DONOR_CLASS_LIST into those values
# each value of  DONOR_CLASS_LIST must be a key in VIRTUAL_CLASS_TRANSLATION. Not used if NEW_COLUMN is not None (or "")
