# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# disable ouput directory from being created
hydra:  
  output_subdir: null  
  run:  
    dir: .

# disable main.log from being created
defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

filepath:
  SHAPEFILE_PATH: null  # shapefile for lidar selecter, to determine the lidar file to select
  DONOR_DIRECTORY: null # directory containing all potential donor lidar files, for lidar selecter
  RECIPIENT_DIRECTORY: null # directory containing all potential donor lidar files, for lidar selecter
  OUTPUT_DIRECTORY_PATH: null # directory containing all potential donor lidar files, for lidar selecter
  RECIPIENT_FILE: null # path to the file that receives points. If done after lidar selecter, is in a subdirectory of OUTPUT_DIRECTORY_PATH
  DONOR_FILE: null # path to the file that gives points. If done after lidar selecter, is in a subdirectory of OUTPUT_DIRECTORY_PATH
  OUTPUT_FILE: null # path to the (resulting) file with added points. 
  INPUT_INDICES_MAP: null # path for the indices map reflecting the changes to the recipient
  OUTPUT_INDICES_MAP: null
  CSV_PATH: null # path to the csv file that log the lidar files to process with patchwork

CRS: 2154

DONOR_CLASS_LIST: [2, 22]
RECIPIENT_CLASS_LIST: [2, 6, 9, 17]

RECIPIENT_SUFFIX: "_recipient"
TILE_SIZE: 1000
PATCH_SIZE: 1 # size of a patch of the grid. Must be a divisor of TILE_SIZE, so for 1000: 0.25, 0.5, 2, 4, 5, 10, 25...
NEW_COLUMN: null # If not null, contains the name of the new column
NEW_COLUMN_SIZE: 8  # must be 8, 16, 32 or 64
VALUE_ADDED_POINTS: 1 # in case of a new column, value of the new point (the other are set to 0)
VIRTUAL_CLASS_TRANSLATION: {2: 69, 22: 70}  # if there is no new column, translate the class of DONOR_CLASS_LIST into those values
# each value of  DONOR_CLASS_LIST must be a key in VIRTUAL_CLASS_TRANSLATION. Not used if NEW_COLUMN is not None (or "")
