
name: ci_deploy_docker

on:
  push:
    # Run deployment on every new version tag and every push to main
    branches: [ "main" ]
    tags: 
      - v*.*.*

env:
  IMAGE_NAME:  ${{ github.repository }}
  REGISTRY: ghcr.io
  TEST_TAG:  ${{ github.repository }}:test

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Set version number
      run: |
        echo "VERSION=v$(python -m version)" >> $GITHUB_ENV

    - name: Check tag and version number consistency
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      # if: ${{ github.event_name == 'tag' }}
      run: |
        if [[ ${{ github.ref_name }} == ${{ env.VERSION }} ]]
        then
        echo "OK: Tag name and version.py (${{ env.VERSION }}) version number (${{ github.ref_name }}) match"
        else
        echo "NOK: Tag name and version.py (${{ env.VERSION }}) version number (${{ github.ref_name }}) don't match"
        exit 1
        fi     

    - name: Build the Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: ${{ env.TEST_TAG }}

    # run the test on the docker image
    - name: Run tests in docker image
      run: >
        docker run
        --ipc=host
        ${{ env.TEST_TAG }}
        python -m pytest ./test -s --log-cli-level DEBUG

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # Build an Docker image with Buildx (don't on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

